### ISSUE TITLE
Use alternative maps

### ISSUE THREAD

**Issue by schiesbn** [siacs/ShareLocationPlugin#5]
Don't know if it is technically possible but it would be great if the plugin would also work without Google Maps and use for example OpenStreetMap instead. Would this be possible?

**Comment by iNPUTmice** [comment]
Have a look at: https://github.com/SamWhited/OpenShareLocationPlugin

**Comment by benediktg** [comment]
OpenShareLocationPlugin now is available here: https://bitbucket.org/SamWhited/opensharelocationplugin/downloads
