### ISSUE TITLE
Aternatives to Google Play Services

### ISSUE THREAD

**Issue by tigre-bleu** [siacs/ShareLocationPlugin#9]
For some reasons, some people do not want to use Google Play Services, or any google owned services.

For instance, an AOSP device, or some device with Android runtime but no Google Play (Like http://jolla.com/)

For these people, it is not possible to use the ShareLocationPlugin in the current state. It would be nice to have a chance to use it anyway by using some alternative Mapping/Geocoding provider.

For instance, we could consider: https://www.mapbox.com/developers/

As a side note, using OpenStreetMap data is in line with the openness of Conversations as a software.

**Comment by andersruneson** [comment]
Maybe you can use
https://play.google.com/store/apps/details?id=com.samwhited.opensharelocationplugin
instead?

**Comment by tigre-bleu** [comment]
Actually on Jolla the android version is 4.1.2 so it cannot be installed as opensharelocationplugin requires 4.2.

Forwareded to https://bitbucket.org/SamWhited/opensharelocationplugin/issues/7/compatibility-with-android-41

**Comment by chpio** [comment]
@andersruneson unfortunately it's not available via f-droid

**Comment by LogicParrot** [comment]
@chpio You can always compile yourself or use [this](http://apps.evozi.com/apk-downloader/).
